services:
  reps-backend-postgres:
    image: bitnami/postgresql
    ports:
      - 5480:5432
    environment: 
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=reps-backend