services:
  reps-backend-postgres:
    image: bitnami/postgresql
    ports:
      - 5480:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=reps-backend
    volumes:
      - db:/var/lib/postgresql/data

  reps-backend-redis:
    image: bitnami/redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  db:
    driver: local
