// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// NOTE: we read `process.env.DATABASE_URL` directly instead of Prisma's strict
// `env()` helper. `env()` throws (PrismaConfigEnvError) whenever the variable is
// not resolvable, which breaks `prisma generate` — client generation only reads
// the schema and needs no database. The URL is only actually used by
// `prisma migrate deploy`, at which point the env var is present.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL ?? "",
  },
});
